### ISSUE TITLE
Multiple domains for single certificate

### ISSUE THREAD

**Issue by jmelfi** [dlapiduz/letsencrypt-s3front#31]
Trying to use this for a domain where it is needed to have a www.example.com and example.com.  When trying to use the original command, only one of the domains is added and the second domain fails.

Is it possible to get both domains incorperated and uploaded to be used in cloudfront?

**Comment by ChrisFernandez** [comment]
+1

**Comment by jrbenito** [comment]
I had no problem with multiple domains, I just tweak the code a little

navigate to command line and remove `-d {}`, now state your domains as "-d www.example.com -d example.com"

This tweak makes up to good contribution I think. I will submit a PR.

**Comment by jrbenito** [comment]
I could do it without problem using multiple -d statements to let´s encrypt command.

I also [setup a lambda][https://vittegleo.com/blog/letsencrypt-lambda-function/]  to run it periodically and renew the certificate. This is not straightforward but do help. Please notice that the blog does not account for multiple -d statements, I tweaked the code a little.

I want to test the solution proposed by [ubergeek42][https://github.com/ubergeek42/lambda-letsencrypt] since it seems more complete and straightforward to setup.

**Comment by jmelfi** [comment]
@jrbenito I know it's possible to create the cert manually with letsencrypt-auto and then upload the certificates.  When I ran the command on in the README with two -d flags for the two domains made two certs and not one certificate with both domains in it.

I am hoping that some details on how to use this tool to sign a single cert with both domains is possible.

**Comment by aripringle** [comment]
From playing around with this some, it seems using multiple -d flags does issue a single certificate from letsencrypt (with SANs configured for the additional domain names), but then attempts to upload that same certificate multiple times to IAM, and update the CloudFront distribution multiple times.

It seems like this method is getting called for every domain: https://github.com/dlapiduz/letsencrypt-s3front/blob/6e99bf4809f117523edc594cefd14ba59bc1c291/letsencrypt_s3front/installer.py#L47

I'm not sure exactly what the best approach would be to fix it, but it seems like it really only needs to run once for the s3front installer, since the certificate is the same every time.
